BC-MOA/MOA-FE

client/src/style/common.js

- 페이지 내에서 공통적으로 사용될 것 같아 제목, 소제목, 안내 text 부분의 스타일을 style/common.js에 추가함.

제목, 소제목 등 공통적인 스타일을 위한 파일 생성

---

client/src/components/gather/addGoal/Goal.js

자유입금 금액 입력 오류 수정

---

client/src/components/gather/addMilitarySavings/AvailableSavingList.js
client/src/components/gather/addMilitarySavings/TermCheckBox.js

netlify 배포시 usememo 오류 수정 테스트 코드 

---

client/src/components/gather/addMilitarySavings/TermCheckBox.js

fix: checks의 null 값 체크

---

client/src/components/gather/addMilitarySavings/TermCheckBox.js

#30 fix : netlify 배포시 오류 코드 수정

---

client/src/components/home/Home.js

test : hello 출력 test

---

client/src/components/common/Modal.js
client/src/components/gather/AddBtn.js
client/src/components/gather/Gather.js
client/src/components/gather/GatherDetail.js
client/src/components/gather/StateGather.js
client/src/components/gather/TransactionEl.js
client/src/components/gather/addGoal/utils.js

모으기 상세 페이지 작업 추가

---

client/src/components/gather/addMilitarySavings/AvailableSavingItemDetail.js

map 함수 warning 코드 수정

---

client/src/components/common/Header.js
client/src/components/reward/MyReward.js

PR 열쇠 클릭시 리워드 페이지로 이동 및 리워드 라우터 이동 플로우 수정

---

client/package-lock.json
client/package.json
client/src/components/reward/MyProducItemDetail.js
client/src/style/color.css

PR 리워드 교환권 페이지 작업

---

client/src/components/reward/MyProducItemDetail.js

PR 교환권 이미지 저장시 버튼 요소 깨짐 발생 이슈 해결

---

client/src/components/reward/MyProductListItem.js
client/src/components/reward/RewardBoxItem.js

리워드 페이지 스타일 수정

---

client/src/components/gather/Gather.js
client/src/components/gather/addMilitarySavings/EditSavingTitle.js

PR 군적금 목표 설정 글자 바이트 제한 기능 추가

---

client/src/components/gather/SetGoalModal.js

목표 설정 모달창 css 작업

---

client/src/components/common/Container.js
client/src/components/gather/MilitaryDetail.js
client/src/components/gather/MilitaryDetailEdit.js
client/src/components/gather/addMilitarySavings/AddMilitarySavingSucess.js
client/src/route/Routes.js

PR 군적금 신청 현황 관련 페이지 작업

---

client/src/components/gather/addMilitarySavings/ApplyDataCard.js
client/src/components/home/BubbleContent.js
client/src/components/reward/MyBoxOpen.js
client/src/components/reward/PopupRewardSelceted.js
client/src/components/reward/Reward.js
client/src/components/reward/RewardItemCard.js
client/src/components/reward/RewardUserInfo.js
client/src/components/signInUp/SignIn.js
client/src/route/Routes.js

PR 리워드 페이지 - 로그인 정보 없을 시 로그인 페이지로 이동 로직 추가

---

client/src/components/gather/addMilitarySavings/MilitaryAutoSavingForm.js
client/src/components/gather/addMilitarySavings/views/AddMilitarySavingsPassward.js
client/src/components/loading/Loading.js

fix : react hook import 경로 변경

---

client/src/components/loading/LoadingStep3.js
client/src/components/signInUp/SignIn.js

feat : /loading에서 /interlock로 이동 코드 추가 및 이동 라우터 링크 url 수정

---

client/src/components/reward/MyBoxOpenModal.js

#116 design : 팝업 버튼 스타일 수정

---

client/src/components/home/BubbleContent.js

design: 홈 화면 군인 캐릭터 svg 파일로 변경

design: 홈 화면 군인 캐릭터 svg 파일로 변경

---

client/src/components/reward/RewardItemCard.js

#129 design : 리워드 선택 이미지 사이즈 조절

---

client/src/components/gather/addMoaSaving/AddMoaSavingPassward.js
client/src/components/gather/addMoaSaving/AddMoaSavingSuccess.js

#109 feat : 제휴통장 비밀번호 저장

---

client/src/components/gather/addGoal/view/Complete.js
client/src/components/gather/detail/StateGather.js
client/src/components/gather/detail/TerminationCard.js
client/src/components/gather/detail/view/AdditionalComplete.js
client/src/components/gather/detail/view/CheckPassword.js
client/src/components/gather/detail/view/TerminationComplete.js
client/src/components/profile/comp/DueProgressBar.js
client/src/components/profile/comp/ProfileCard.js

- 비밀번호 체크 - 제휴 통장 개설 시 설정한 비밀번호 적용하도록 코드 수정 ( 이전: 더미데이터 사용)
- 목표, 비상금 설정 완료 페이지 - 입금계좌 부분 수정

비밀번호 체크 - 제휴 통장 개설 시 설정한 비밀번호 적용

---

client/src/components/gather/addGoal/view/Goal.js

chore: 오타 수정

---

client/src/components/gather/detail/StateGather.js
client/src/components/gather/detail/TerminationCard.js

홈화면: 적금 카드별 위아래 마진 값 추가
